name: Pipeline

on:
  push:
    branches:
      - main

jobs:
  check-quality-and-build-preview:
    runs-on: ubuntu-latest
    name: Check quality and build
    steps:
    - uses: actions/checkout@v2
    - uses: bahmutov/npm-install@v1
    - run: yarn --frozen-lockfile

    - name: Check type
      run: yarn type

    - name: Check code
      run: yarn lint

    - name: Build
      run: yarn build

    - uses: actions/upload-artifact@v2
      with:
        name: dist-preview
        path: dist/

  deploy-preview-to-ftp:
    needs: check-quality-and-build-preview
    runs-on: ubuntu-latest
    name: Deploy preview to FTP
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: dist-preview
        path: dist/

    - name: Deploy to ftp
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        METHOD: sftp
        PORT: ${{ secrets.FTP_PORT }}
        LOCAL_DIR: dist
        REMOTE_DIR: /www/rc-dynamic/preview
        ARGS: --delete --verbose --parallel=100
